name: Check Helm Charts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: helm-check-time-server
      uses: igabaydulin/helm-check-action@0.2.1
      env:
        CHART_LOCATION: ./time-server
        CHART_VALUES: ./time-server/values.yaml
    - name: helm-check-auth-server
      uses: igabaydulin/helm-check-action@0.2.1
      env:
        CHART_LOCATION: ./auth-server
        CHART_VALUES: ./auth-server/values.yaml
